name: 'Deploy on DEV'

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  
  build:

    runs-on: ubuntu-latest
    
    steps:

      - name: 'Carregar variáveis compartilhadas'
        uses: vladperche/base_cicd_np/.github/actions/share-variables@main

      - name: 'Executar Template'
        uses: vladperche/base_cicd_templates/.github/actions/install-dependencies@main
        with:
          account-id: $AWS_ACCOUNT_ID
          env-name: $AWS_ENVIRONMENT
          node-version: $NODE_VERSION

