name: 'Deploy on DEV'

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  
  get-vars:
    uses: vladperche/base_cicd_np/.github/workflows/export-vars.yml@main

  build:

    runs-on: ubuntu-latest
    needs: get-vars
    
    steps:

      - name: 'Executar Template'
        uses: vladperche/base_cicd_templates/.github/actions/install-dependencies@main
        with:
          account-id: ${{needs.get-vars.outputs.AWS_ACCOUNT_ID}}
          env-name: ${{needs.get-vars.outputs.AWS_ENVIRONMENT}}
          node-version: ${{needs.get-vars.outputs.NODE_VERSION}}

