name: 'Deploy on DEV'

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  
  build:
    
    steps:

      - name: 'Executar Template'
        uses: vladperche/base_cicd_templates/.github/actions/install-dependencies@main
        with:
          node-version: '20.x'

